### ISSUE TITLE
Ask about the corresponding paper

### ISSUE THREAD

**Issue by Wooooov** [anhbui0803/Course-Recommendation-GA#1]
I found it was a very interesting work! I just want to ask if there is a corresponding paper for this code? If it is not too much trouble, could you please provide me with the paper or direct me to where I can obtain it? I appreciate any assistance you can offer.

**Comment by anhbui0803** [comment]
Hi Wooooov, sorry for the late reply. I'm very happy that there is someone interesting in my personal project, I will send you some related paper that I used to  research ASAP.

**Comment by Wooooov** [comment]
Wow, so thank you for your kindness. Welcome to send relevant reference papers to my email: 2569858812@qq.com. It will be very helpful for me.

**Comment by anhbui0803** [comment]
I just sent you the email, you can check it out, wish you will find it useful. If there's nothing else, please close this issue, thank you.
